create schema Weasley;

-- use schema Weasley;

create table Weasley.Customer (
    customerId bigint generated by default as identity,
    email varchar(255),
    firstName varchar(25),
    lastName varchar(30),
    phoneNumber varchar(25),
    primary key (customerId)
);
